//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/TabNav.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TabNav: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TabNav()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TabNav"",
    ""maps"": [
        {
            ""name"": ""actionmapree"",
            ""id"": ""c211a8d3-f20c-4528-a9d0-1d310bc9f4b6"",
            ""actions"": [
                {
                    ""name"": ""TabCycle"",
                    ""type"": ""Button"",
                    ""id"": ""ed132f09-47be-4ed7-a3d8-89827810ac6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1b56db8d-0192-45d5-9477-b0ec7b758c58"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabCycle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // actionmapree
        m_actionmapree = asset.FindActionMap("actionmapree", throwIfNotFound: true);
        m_actionmapree_TabCycle = m_actionmapree.FindAction("TabCycle", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // actionmapree
    private readonly InputActionMap m_actionmapree;
    private List<IActionmapreeActions> m_ActionmapreeActionsCallbackInterfaces = new List<IActionmapreeActions>();
    private readonly InputAction m_actionmapree_TabCycle;
    public struct ActionmapreeActions
    {
        private @TabNav m_Wrapper;
        public ActionmapreeActions(@TabNav wrapper) { m_Wrapper = wrapper; }
        public InputAction @TabCycle => m_Wrapper.m_actionmapree_TabCycle;
        public InputActionMap Get() { return m_Wrapper.m_actionmapree; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActionmapreeActions set) { return set.Get(); }
        public void AddCallbacks(IActionmapreeActions instance)
        {
            if (instance == null || m_Wrapper.m_ActionmapreeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ActionmapreeActionsCallbackInterfaces.Add(instance);
            @TabCycle.started += instance.OnTabCycle;
            @TabCycle.performed += instance.OnTabCycle;
            @TabCycle.canceled += instance.OnTabCycle;
        }

        private void UnregisterCallbacks(IActionmapreeActions instance)
        {
            @TabCycle.started -= instance.OnTabCycle;
            @TabCycle.performed -= instance.OnTabCycle;
            @TabCycle.canceled -= instance.OnTabCycle;
        }

        public void RemoveCallbacks(IActionmapreeActions instance)
        {
            if (m_Wrapper.m_ActionmapreeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IActionmapreeActions instance)
        {
            foreach (var item in m_Wrapper.m_ActionmapreeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ActionmapreeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ActionmapreeActions @actionmapree => new ActionmapreeActions(this);
    public interface IActionmapreeActions
    {
        void OnTabCycle(InputAction.CallbackContext context);
    }
}
